### PR TITLE
fix: there is no errors when sql is incorrect

### LINKED ISSUE #122: Without any error return even I give it an invalid sql
See the following statements:

```
session.ExecuteStatement()
```

I found it just skip to check the status code.

### PR DESCRIPTION
**Pull request by LinuxSuRen**
fix #122

### CODE REVIEW

File: client/session.go [hunk 1]
```diff
@@ -442,26 +442,33 @@ func (s *Session) SetTimeZone(timeZone string) (r *common.TSStatus, err error) {
...
 
 	if err != nil && resp == nil {
 		if s.reconnect() {
 			request.SessionId = s.sessionId
 			request.StatementId = s.requestStatementId
-			resp, err = s.client.ExecuteStatement(context.Background(), &request)
+			resp, err = s.client.ExecuteStatement(ctx, &request)
 		}
 	}
+	if resp.Status != nil && resp.Status.Code != 200 {
```
Comment (shuwenwei) [inline client/session.go:461]: VerifuSuccess function can be used here

Comment (LinuxSuRen) [reply client/session.go:461]: Sure.

**Comment by LinuxSuRen** [comment]
hi @shuwenwei , my tool formatted some code lines automatically. Please let me know if you think it's not acceptable. And thanks for your time.

**Review by shuwenwei — APPROVED** [review]

**Comment by shuwenwei** [comment]
> hi @shuwenwei , my tool formatted some code lines automatically. Please let me know if you think it's not acceptable. And thanks for your time.


I think it is ok.

**Comment by JackieTien97** [comment]
@LinuxSuRen please cp it to [dev/1.3](https://github.com/apache/iotdb-client-go/tree/dev/1.3)

**Comment by LinuxSuRen** [comment]
> @LinuxSuRen please cp it to [dev/1.3](https://github.com/apache/iotdb-client-go/tree/dev/1.3)

I didn't get your point. Could you tell more?

**Comment by shuwenwei** [comment]
> > @LinuxSuRen please cp it to [dev/1.3](https://github.com/apache/iotdb-client-go/tree/dev/1.3?rgh-link-date=2025-03-28T05%3A40%3A57Z)
> 
> I didn't get your point. Could you tell more?
cherry pick this commit to dev/1.3 branch and create another PR whose target branch is dev/1.3
截屏2025-03-31 10 46 56

**Comment by LinuxSuRen** [comment]
So, if contributors should not create a PR against the `main` branch?

I'm wondering if it's possible to set `dev/x.x` as the default branch. For example, for now set the default branch to be `dev/1.3.

**Comment by shuwenwei** [comment]
> So, if contributors should not create a PR against the `main` branch?
> 
> I'm wondering if it's possible to set `dev/x.x` as the default branch. For example, for now set the default branch to be `dev/1.3.

The main branch can be considered 2.0, but dev/1.3 branch is also being maintained
